#version: 2.1
#
#orbs:
#  android: circleci/android@2.4.0
#
#jobs:
#  build:
#    docker:
#      - image: cimg/android:2024.01-ndk
#    steps:
#      - checkout
#      - restore_cache:
#          key: android-orb-v1-
#      - run:
#          name: Chmod permissions
#          command: sudo chmod +x ./gradlew
#      - run:
#          name: Download Dependencies
#          command: ./gradlew androidDependencies
#      - save_cache:
#          key: 'android-orb-v1-{{ epoch }}'
#          paths:
#            - ~/.android/build-cache
#            - ~/.android/cache
#      - run:
#          name: Run Build
#          command: ./gradlew build
#      - store_artifacts:
#          path: app/build/reports
#          destination: reports
#      - run:
#          name: Run Tests
#          command: ./gradlew lint test
#      - store_test_results:
#          path: app/build/test-results
#      - store_artifacts:
#          path: app/build/outputs/apk/debug/
#          destination: artifact-file

#version: 2.1
#
#orbs:
#  android: circleci/android@2.4.0
#
#jobs:
#  build:
#    docker:
##      - image: cimg/android:2024.01-ndk
#      - image: cimg/android:2023.11
#    environment:
#      _JAVA_OPTIONS: "-Xmx4g -XX:+UseParallelGC"
#      JDK_VERSION: 17 # Increase JVM heap size
#      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512 -XX:+HeapDumpOnOutOfMemoryError"
#
#    steps:
#      - checkout
#
#      - restore_cache:
#          keys:
#            - android-proguard-cache-{{ .Branch }}-{{ checksum "app/proguard-rules.pro" }}
#            - android-proguard-cache-
#
#      - run:
#          name: Chmod permissions
##          command: sudo chmod +x ./gradlew
#          command: chmod +x ./gradlew && ls -1 ./gradlew
#
#      - run:
#          name: Clean project
#          command: ./gradlew clean
#
#      - run:
#          name: Download Dependencies
#          command: ./gradlew androidDependencies
#
#      - save_cache:
#          paths:
#            - ~/.android/build-cache
#            - ~/.gradle/caches
#            - ~/.gradle/wrapper
#            - app/build/intermediates
#          key: android-proguard-cache-{{ .Branch }}-{{ checksum "app/proguard-rules.pro" }}
#
#      - run:
#          name: Build with ProGuard
#          command: ./gradlew assembleRelease --no-daemon --stacktrace --info
##          command: ./gradlew :app:assembleDebug :app:assembleRelease :core:assembleDebug :core:assembleRelease --no-daemon --max-workers=2
#
#      - store_artifacts:
#          path: app/build/reports
#          destination: reports
#
#      - run:
#          name: Run Tests
#          command: ./gradlew lint test
#
#      - store_test_results:
#          path: app/build/test-results
#
#      - store_artifacts:
#          path: app/build/outputs/apk/debug/
#          destination: artifact-file-debug
#
#      - store_artifacts:
#          path: app/build/outputs/apk/release/
#          destination: artifact-file-release
#
#      - store_artifacts:
#          path: app/build/outputs
#          destination: artifacts
version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.11

    environment:
      _JAVA_OPTIONS: "-Xmx4g -XX:+UseParallelGC"
      JDK_VERSION: 17
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"

    steps:
      - checkout

      - restore_cache:
          keys:
#            - android-proguard-cache-{{ .Branch }}-{{ checksum "app/proguard-rules.pro" }}
            - android-proguard-cache-

      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew && ls -l ./gradlew
#      tambahkan eksplisit ksp
      - run:
          name: Generate KSP Files
          command: ./gradlew kspDebugKotlin kspReleaseKotlin kspDebugUnitTestKotlin kspReleaseUnitTestKotlin
      - run:
          name: Update KSP
          command: ./gradlew kspDebugKotlin kspReleaseKotlin --no-daemon

      - run:
          name: Install SDK Build Tools 34.0.0
          command: sdkmanager "build-tools;34.0.0"

#      - run:
#          name: Debug ProGuard
#          command: ./gradlew assembleRelease --stacktrace --info --no-daemon
      #      tambahkan
      - run:
          name: Install SDK Build Tools 33.0.2
          command: sdkmanager "build-tools;33.0.2"

      - run:
          name: Clean project
          command: ./gradlew clean

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.android/build-cache
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - app/build/intermediates
          key: android-proguard-cache-{{ .Branch }}-{{ checksum "app/proguard-rules.pro" }}

      - run:
          name: Build with ProGuard
          command: ./gradlew assembleRelease --no-daemon --stacktrace --info

      - store_artifacts:
          path: app/build/outputs
          destination: artifacts

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results

